//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub create_time: Option<String>,
    pub permission_url: Option<String>,
    pub r#type: Option<String>,
    pub method: Option<String>,
    pub group: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::permission_role::Entity")]
    PermissionRole,
}

impl Related<super::permission_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermissionRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
