//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::category::Entity as Category;
pub use super::exception::Entity as Exception;
pub use super::post::Entity as Post;
pub use super::users::Entity as Users;
