//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "product_sku_name_value")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_id: i32,
    pub sku_name_id: i32,
    pub sku_value_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product::Entity",
        from = "Column::ProductId",
        to = "super::product::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Product,
    #[sea_orm(
        belongs_to = "super::product_sku_name::Entity",
        from = "Column::SkuNameId",
        to = "super::product_sku_name::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProductSkuName,
    #[sea_orm(
        belongs_to = "super::product_sku_value::Entity",
        from = "Column::SkuValueId",
        to = "super::product_sku_value::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProductSkuValue,
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

impl Related<super::product_sku_name::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductSkuName.def()
    }
}

impl Related<super::product_sku_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductSkuValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
