server:
  name: "d_blog"
  address: "0.0.0.0:5800"
  ssl: false
  cors_allow_origin:
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"

database:
  database_url: "sqlite:data/demo.db"

jwt:
  jwt_secret: "secret"
  jwt_exp: 6000

cert:
  cert: "config/certs/cert.pem"
  key: "config/certs/key.pem"

log:
  filter_level: "info"        # Available options: "debug", "info", "warn", "error"
  with_ansi: true
  to_stdout: true
  directory: "./logs"
  file_name: "my-service.log"
  rolling: "daily"            # Available options: "minutely", "hourly", "daily", "never"